apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hello-world-ns.yaml
  - hello-world-deployment.yaml
  - hello-world-service.yaml

namespace: hello-world-ns

commonLabels:
  managed-by: kustomize
  project: aks-cluster-demo
